### ISSUE TITLE
Instagram QueryError

### ISSUE THREAD

**Issue by butterflyx** [iojw/socialscan#17] opened 2020-02-24 16:10 UTC
Using socialscan I get repeatedly the error:
`Instagram: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.`

Using a proxy, doesn't solve the issue, as only http proxies supported at the moment:
`Instagram: ClientConnectorCertificateError - Cannot connect to host www.instagram.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')]
`
Proxy used: 
`http://80.187.140.26:8080`

**Comment by iojw** [comment] 2020-03-04 14:40
@butterflyx Are you still facing this issue? Normally it is caused by too many requests sent in a short period of time. Is that the case or does it occur even with a single query?

As for the proxy, yes I'm afraid only http proxies are supported at the comment. This is a limitation of aiohttp, the library I'm using for executing requests

**Comment by harismustajbasic** [comment] 2020-03-22 18:10
> @butterflyx Are you still facing this issue? Normally it is caused by too many requests sent in a short period of time. Is that the case or does it occur even with a single query?
> 
> As for the proxy, yes I'm afraid only http proxies are supported at the comment. This is a limitation of aiohttp, the library I'm using for executing requests

This still happens, even with a single query and even if sending only one request. Could this be something to do with changes on Instagram side?

**Comment by iojw** [comment] 2020-03-23 15:50
@herecomesharis Instagram is still working well on my own computer and on Travis so it is difficult for me to troubleshoot this error. What region are you from? Maybe you are being served a different version of Instagram.

**Comment by herecomesharis** [comment] 2020-04-09 14:01
> @herecomesharis Instagram is still working well on my own computer and on Travis so it is difficult for me to troubleshoot this error. What region are you from? Maybe you are being served a different version of Instagram.

Hi! Sorry for my late reply, hope you will see this.
I'm from EU. To highlight the issue I pasted everything from my console so you can check it out - https://pastebin.com/1bi1Q9RY
Maybe I did something wrong?

Br

**Comment by butterflyx** [comment] 2020-04-30 19:55
@iojw : missed this notification as well, sorry!

Yes, this seems an error due to local restrictions of Instagram. 
I'm in the EU as well and still get the same error.
Using a VPN to get an IP within the US solves this issue for me.

Maybe worth noticing.

**Comment by iojw** [comment] 2020-05-06 10:21
@butterflyx Oh I see, thanks for checking it out. I’d like to keep this issue open to fix this when I get time. In the meantime, you’ll have to use a VPN @herecomesharis

**Comment by herecomesharis** [comment] 2020-05-06 18:02
@butterflyx @iojw 
Thank you both for your assistance. Will try it out and hope it works.

**Comment by manawenuz** [comment] 2020-10-22 06:49
I'm facing the same issue, tried it on my few servers, (all in europe, and i'm also in caucuses), but it worked on one of my servers, which is in middle east.
thanks

**Comment by iojw** [comment] 2020-10-30 02:32
If one of you could run the latest version of socialscan (1.4.0) with the `--debug` flag and provide the output, it would make it easier to debug this problem.

**Comment by manawenuz** [comment] 2020-10-31 03:21
i installed it using pip, so i was on 1.3.0, upgraded it from github to 1.4.1, and it works here now.

**Comment by iojw** [comment] 2020-10-31 07:34
@manawenuz I didn't change anything about the code so look like something changed on Instagram's end that fixed it.

**Comment by iojw** [comment] 2020-11-02 03:09
Going to close this for now as it appears to be fixed, do let me know if this issue still occurs for Instagram by providing debug output.

**Closed by iojw** 2020-11-02 03:09 UTC
Labels: bug
